package pt.properia.api.modules.search.application.dto;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record ListingSearchItemDto(
    UUID id,
    String publicId,
    UUID advertiserId,
    String title,
    String businessType,
    String propertyType,
    String status,
    String visibilityStatus,
    boolean isFeatured,
    BigDecimal priceAmount,
    String priceCurrency,
    BigDecimal condoFee,
    BigDecimal propertyTaxAnnual,
    BigDecimal municipalTaxEstimate,
    BigDecimal depositRequired,
    int bedrooms,
    BigDecimal bathrooms,
    int suites,
    Integer garageSpaces,
    Integer parkingSpaces,
    BigDecimal usableAreaM2,
    BigDecimal grossAreaM2,
    BigDecimal lotAreaM2,
    String city,
    String district,
    String parish,
    String neighborhood,
    String street,
    String postalCode,
    String locationPrecision,
    Double latitude,
    Double longitude,
    String heroImageUrl,
    List<String> imageUrls,
    String floorPlanUrl,
    String youtubeVideoUrl,
    String descriptionShort,
    String energyRating,
    String conditionStatus,
    String furnishedStatus,
    boolean hasGarage,
    boolean hasPrivateParking,
    boolean hasBalcony,
    boolean hasTerrace,
    boolean hasGarden,
    boolean hasPool,
    boolean hasElevator,
    boolean hasNaturalLight,
    boolean hasEquippedKitchen,
    boolean hasBuiltInClosets,
    boolean hasDoubleGlazing,
    boolean hasSolarPanels,
    boolean hasBarbecue,
    boolean hasLaundryArea,
    String poolType,
    List<String> featureTags,
    Integer floorNumber,
    Integer totalFloors,
    Integer constructionYear,
    Integer renovationYear,
    String sunExposure,
    String tipologia,
    boolean isImmediatelyAvailable,
    String availableFrom,
    Instant publishedAt,
    Instant updatedAt,
    String zoneLabelPrimary,
    String zoneSummaryShort,
    int detailViewsTotal,
    PriceHistorySnapshotDto priceHistorySnapshot,
    String virtualTourUrl,
    String virtualTourStatus,
    CommuteSummaryDto commuteSummary
) {
    public ListingSearchItemDto withCommuteSummary(CommuteSummaryDto cs) {
        return new ListingSearchItemDto(
            id, publicId, advertiserId, title, businessType, propertyType, status,
            visibilityStatus, isFeatured, priceAmount, priceCurrency,
            condoFee, propertyTaxAnnual, municipalTaxEstimate, depositRequired,
            bedrooms, bathrooms, suites, garageSpaces, parkingSpaces,
            usableAreaM2, grossAreaM2, lotAreaM2,
            city, district, parish, neighborhood, street, postalCode, locationPrecision,
            latitude, longitude, heroImageUrl, imageUrls, floorPlanUrl, youtubeVideoUrl,
            descriptionShort, energyRating, conditionStatus, furnishedStatus,
            hasGarage, hasPrivateParking, hasBalcony, hasTerrace, hasGarden,
            hasPool, hasElevator, hasNaturalLight, hasEquippedKitchen, hasBuiltInClosets,
            hasDoubleGlazing, hasSolarPanels, hasBarbecue, hasLaundryArea, poolType,
            featureTags, floorNumber, totalFloors, constructionYear, renovationYear,
            sunExposure, tipologia, isImmediatelyAvailable, availableFrom,
            publishedAt, updatedAt, zoneLabelPrimary, zoneSummaryShort,
            detailViewsTotal, priceHistorySnapshot, virtualTourUrl, virtualTourStatus,
            cs
        );
    }
}
