package pt.properia.api.modules.listings.application.dto;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

public record ListingCardDto(
    UUID id,
    String publicId,
    UUID advertiserId,
    String status,
    String businessType,
    String propertyType,
    String title,
    BigDecimal priceAmount,
    String priceCurrency,
    int bedrooms,
    BigDecimal bathrooms,
    int suites,
    BigDecimal usableAreaM2,
    BigDecimal grossAreaM2,
    String city,
    String district,
    String municipality,
    String parish,
    String neighborhood,
    String street,
    String postalCode,
    String heroImageUrl,
    String descriptionRaw,
    String energyRating,
    String conditionStatus,
    String furnishedStatus,
    Double latitude,
    Double longitude,
    String zoneLabelPrimary,
    String zoneSummaryShort,
    Instant publishedAt,
    Instant firstPublishedAt,
    Instant createdAt
) {}
